function(msf_apply_project_warnings warnings_as_errors)
    if(MSVC)
        add_compile_options(/W4)
        if(${warnings_as_errors})
            add_compile_options(/WX)
        endif()
    else()
        add_compile_options(-Wall -Wextra -Wpedantic)
        if(${warnings_as_errors})
            add_compile_options(-Werror)
        endif()
    endif()
endfunction()
